var annotated_dup =
[
    [ "argparse", "namespaceargparse.html", [
      [ "details", "namespaceargparse_1_1details.html", [
        [ "ConsumeHexPrefixResult", "structargparse_1_1details_1_1_consume_hex_prefix_result.html", "structargparse_1_1details_1_1_consume_hex_prefix_result" ],
        [ "HasContainerTraits", "structargparse_1_1details_1_1_has_container_traits.html", null ],
        [ "HasContainerTraits< std::string >", "structargparse_1_1details_1_1_has_container_traits_3_01std_1_1string_01_4.html", null ],
        [ "HasContainerTraits< std::string_view >", "structargparse_1_1details_1_1_has_container_traits_3_01std_1_1string__view_01_4.html", null ],
        [ "HasContainerTraits< T, std::void_t< typename T::value_type, decltype(std::declval< T >().begin()), decltype(std::declval< T >().end()), decltype(std::declval< T >().size())> >", "structargparse_1_1details_1_1_has_container_traits_3_01_t_00_01std_1_1void__t_3_01typename_01_t_45bf9f9c91ca7c1cb49ea6280ce472db.html", null ],
        [ "HasStreamableTraits", "structargparse_1_1details_1_1_has_streamable_traits.html", null ],
        [ "HasStreamableTraits< T, std::void_t< decltype(std::declval< std::ostream & >()<< std::declval< T >())> >", "structargparse_1_1details_1_1_has_streamable_traits_3_01_t_00_01std_1_1void__t_3_01decltype_07stdc91fa09967c0b4a20df453e08636ed8.html", null ],
        [ "parse_number", "structargparse_1_1details_1_1parse__number.html", "structargparse_1_1details_1_1parse__number" ],
        [ "parse_number< T >", "structargparse_1_1details_1_1parse__number_3_01_t_01_4.html", "structargparse_1_1details_1_1parse__number_3_01_t_01_4" ],
        [ "parse_number< T, chars_format::fixed >", "structargparse_1_1details_1_1parse__number_3_01_t_00_01chars__format_1_1fixed_01_4.html", "structargparse_1_1details_1_1parse__number_3_01_t_00_01chars__format_1_1fixed_01_4" ],
        [ "parse_number< T, chars_format::general >", "structargparse_1_1details_1_1parse__number_3_01_t_00_01chars__format_1_1general_01_4.html", "structargparse_1_1details_1_1parse__number_3_01_t_00_01chars__format_1_1general_01_4" ],
        [ "parse_number< T, chars_format::hex >", "structargparse_1_1details_1_1parse__number_3_01_t_00_01chars__format_1_1hex_01_4.html", "structargparse_1_1details_1_1parse__number_3_01_t_00_01chars__format_1_1hex_01_4" ],
        [ "parse_number< T, chars_format::scientific >", "structargparse_1_1details_1_1parse__number_3_01_t_00_01chars__format_1_1scientific_01_4.html", "structargparse_1_1details_1_1parse__number_3_01_t_00_01chars__format_1_1scientific_01_4" ],
        [ "parse_number< T, radix_16 >", "structargparse_1_1details_1_1parse__number_3_01_t_00_01radix__16_01_4.html", "structargparse_1_1details_1_1parse__number_3_01_t_00_01radix__16_01_4" ]
      ] ],
      [ "Argument", "classargparse_1_1_argument.html", "classargparse_1_1_argument" ],
      [ "ArgumentParser", "classargparse_1_1_argument_parser.html", "classargparse_1_1_argument_parser" ]
    ] ],
    [ "ml", "namespaceml.html", [
      [ "Add", "classml_1_1_add.html", "classml_1_1_add" ],
      [ "Algorithm", "classml_1_1_algorithm.html", "classml_1_1_algorithm" ],
      [ "Constant", "classml_1_1_constant.html", "classml_1_1_constant" ],
      [ "Environment", "classml_1_1_environment.html", "classml_1_1_environment" ],
      [ "Expression", "classml_1_1_expression.html", "classml_1_1_expression" ],
      [ "KeyNotFoundException", "classml_1_1_key_not_found_exception.html", null ],
      [ "Logger", "classml_1_1_logger.html", "classml_1_1_logger" ],
      [ "math_error", "classml_1_1math__error.html", "classml_1_1math__error" ],
      [ "NotImplementedException", "classml_1_1_not_implemented_exception.html", null ],
      [ "Variable", "classml_1_1_variable.html", "classml_1_1_variable" ]
    ] ],
    [ "QT_WARNING_DISABLE_DEPRECATED", "namespace_q_t___w_a_r_n_i_n_g___d_i_s_a_b_l_e___d_e_p_r_e_c_a_t_e_d.html", [
      [ "qt_meta_stringdata_CLASSMainWindowENDCLASS_t", "struct_q_t___w_a_r_n_i_n_g___d_i_s_a_b_l_e___d_e_p_r_e_c_a_t_e_d_1_1qt__meta__stringdata___c_l_aa48c4f7148681482a19d10736c6999b5.html", "struct_q_t___w_a_r_n_i_n_g___d_i_s_a_b_l_e___d_e_p_r_e_c_a_t_e_d_1_1qt__meta__stringdata___c_l_aa48c4f7148681482a19d10736c6999b5" ],
      [ "qt_meta_stringdata_CLASSMFlowlineDialogENDCLASS_t", "struct_q_t___w_a_r_n_i_n_g___d_i_s_a_b_l_e___d_e_p_r_e_c_a_t_e_d_1_1qt__meta__stringdata___c_l_ad6efd3224cb7302955083afae4c054d3.html", "struct_q_t___w_a_r_n_i_n_g___d_i_s_a_b_l_e___d_e_p_r_e_c_a_t_e_d_1_1qt__meta__stringdata___c_l_ad6efd3224cb7302955083afae4c054d3" ],
      [ "qt_meta_stringdata_CLASSMJunctionDialogENDCLASS_t", "struct_q_t___w_a_r_n_i_n_g___d_i_s_a_b_l_e___d_e_p_r_e_c_a_t_e_d_1_1qt__meta__stringdata___c_l_a51552e9b14bbd7b7a74cd83b91058bbc.html", "struct_q_t___w_a_r_n_i_n_g___d_i_s_a_b_l_e___d_e_p_r_e_c_a_t_e_d_1_1qt__meta__stringdata___c_l_a51552e9b14bbd7b7a74cd83b91058bbc" ],
      [ "qt_meta_stringdata_CLASSMSinkDialogENDCLASS_t", "struct_q_t___w_a_r_n_i_n_g___d_i_s_a_b_l_e___d_e_p_r_e_c_a_t_e_d_1_1qt__meta__stringdata___c_l_ada50ba29788fd693ca928596d4bc92f8.html", "struct_q_t___w_a_r_n_i_n_g___d_i_s_a_b_l_e___d_e_p_r_e_c_a_t_e_d_1_1qt__meta__stringdata___c_l_ada50ba29788fd693ca928596d4bc92f8" ],
      [ "qt_meta_stringdata_CLASSMSourceDialogENDCLASS_t", "struct_q_t___w_a_r_n_i_n_g___d_i_s_a_b_l_e___d_e_p_r_e_c_a_t_e_d_1_1qt__meta__stringdata___c_l_aea470d04f84491bf317778d270cb8909.html", "struct_q_t___w_a_r_n_i_n_g___d_i_s_a_b_l_e___d_e_p_r_e_c_a_t_e_d_1_1qt__meta__stringdata___c_l_aea470d04f84491bf317778d270cb8909" ],
      [ "qt_meta_stringdata_CLASSMWellWidgetENDCLASS_t", "struct_q_t___w_a_r_n_i_n_g___d_i_s_a_b_l_e___d_e_p_r_e_c_a_t_e_d_1_1qt__meta__stringdata___c_l_ad8ddc03852ff40fb4111ea90c3868f61.html", "struct_q_t___w_a_r_n_i_n_g___d_i_s_a_b_l_e___d_e_p_r_e_c_a_t_e_d_1_1qt__meta__stringdata___c_l_ad8ddc03852ff40fb4111ea90c3868f61" ],
      [ "qt_meta_stringdata_CLASSMWellWindowENDCLASS_t", "struct_q_t___w_a_r_n_i_n_g___d_i_s_a_b_l_e___d_e_p_r_e_c_a_t_e_d_1_1qt__meta__stringdata___c_l_a9aeec70dd11c2bdaf58a2b85bebb52cd.html", "struct_q_t___w_a_r_n_i_n_g___d_i_s_a_b_l_e___d_e_p_r_e_c_a_t_e_d_1_1qt__meta__stringdata___c_l_a9aeec70dd11c2bdaf58a2b85bebb52cd" ],
      [ "qt_meta_stringdata_CLASSsinkDialogENDCLASS_t", "struct_q_t___w_a_r_n_i_n_g___d_i_s_a_b_l_e___d_e_p_r_e_c_a_t_e_d_1_1qt__meta__stringdata___c_l_aad177f714c209ea0256bf158870b913f.html", "struct_q_t___w_a_r_n_i_n_g___d_i_s_a_b_l_e___d_e_p_r_e_c_a_t_e_d_1_1qt__meta__stringdata___c_l_aad177f714c209ea0256bf158870b913f" ],
      [ "qt_meta_stringdata_CLASSTFlowlineItemENDCLASS_t", "struct_q_t___w_a_r_n_i_n_g___d_i_s_a_b_l_e___d_e_p_r_e_c_a_t_e_d_1_1qt__meta__stringdata___c_l_a4410d910dbc87da40b5a27bd5c3556df.html", "struct_q_t___w_a_r_n_i_n_g___d_i_s_a_b_l_e___d_e_p_r_e_c_a_t_e_d_1_1qt__meta__stringdata___c_l_a4410d910dbc87da40b5a27bd5c3556df" ],
      [ "qt_meta_stringdata_CLASSTGraphicsSceneENDCLASS_t", "struct_q_t___w_a_r_n_i_n_g___d_i_s_a_b_l_e___d_e_p_r_e_c_a_t_e_d_1_1qt__meta__stringdata___c_l_a569f227ab2369a43267ee20c05543781.html", "struct_q_t___w_a_r_n_i_n_g___d_i_s_a_b_l_e___d_e_p_r_e_c_a_t_e_d_1_1qt__meta__stringdata___c_l_a569f227ab2369a43267ee20c05543781" ],
      [ "qt_meta_stringdata_CLASSTGraphicsViewENDCLASS_t", "struct_q_t___w_a_r_n_i_n_g___d_i_s_a_b_l_e___d_e_p_r_e_c_a_t_e_d_1_1qt__meta__stringdata___c_l_ac8b0485d819465da8c87978df8c3f158.html", "struct_q_t___w_a_r_n_i_n_g___d_i_s_a_b_l_e___d_e_p_r_e_c_a_t_e_d_1_1qt__meta__stringdata___c_l_ac8b0485d819465da8c87978df8c3f158" ],
      [ "qt_meta_stringdata_CLASSTMultiflowItemENDCLASS_t", "struct_q_t___w_a_r_n_i_n_g___d_i_s_a_b_l_e___d_e_p_r_e_c_a_t_e_d_1_1qt__meta__stringdata___c_l_afe27076147592e6d8faed72ebeab28a4.html", "struct_q_t___w_a_r_n_i_n_g___d_i_s_a_b_l_e___d_e_p_r_e_c_a_t_e_d_1_1qt__meta__stringdata___c_l_afe27076147592e6d8faed72ebeab28a4" ],
      [ "qt_meta_stringdata_CLASSTSinkItemENDCLASS_t", "struct_q_t___w_a_r_n_i_n_g___d_i_s_a_b_l_e___d_e_p_r_e_c_a_t_e_d_1_1qt__meta__stringdata___c_l_a3beca78709bc34d41889cbe1fbd0fc6e.html", "struct_q_t___w_a_r_n_i_n_g___d_i_s_a_b_l_e___d_e_p_r_e_c_a_t_e_d_1_1qt__meta__stringdata___c_l_a3beca78709bc34d41889cbe1fbd0fc6e" ],
      [ "qt_meta_stringdata_CLASSTSourceItemENDCLASS_t", "struct_q_t___w_a_r_n_i_n_g___d_i_s_a_b_l_e___d_e_p_r_e_c_a_t_e_d_1_1qt__meta__stringdata___c_l_ad5fd93a0d35504cb1dea6eda46121c03.html", "struct_q_t___w_a_r_n_i_n_g___d_i_s_a_b_l_e___d_e_p_r_e_c_a_t_e_d_1_1qt__meta__stringdata___c_l_ad5fd93a0d35504cb1dea6eda46121c03" ],
      [ "qt_meta_stringdata_CLASSTTabWidgetENDCLASS_t", "struct_q_t___w_a_r_n_i_n_g___d_i_s_a_b_l_e___d_e_p_r_e_c_a_t_e_d_1_1qt__meta__stringdata___c_l_a52d2a1720f90c70c3ea8671e5b634b66.html", "struct_q_t___w_a_r_n_i_n_g___d_i_s_a_b_l_e___d_e_p_r_e_c_a_t_e_d_1_1qt__meta__stringdata___c_l_a52d2a1720f90c70c3ea8671e5b634b66" ],
      [ "qt_meta_stringdata_CLASSTTreeWidgetENDCLASS_t", "struct_q_t___w_a_r_n_i_n_g___d_i_s_a_b_l_e___d_e_p_r_e_c_a_t_e_d_1_1qt__meta__stringdata___c_l_a553e20876357be71ce89bdb01628f81a.html", "struct_q_t___w_a_r_n_i_n_g___d_i_s_a_b_l_e___d_e_p_r_e_c_a_t_e_d_1_1qt__meta__stringdata___c_l_a553e20876357be71ce89bdb01628f81a" ],
      [ "qt_meta_stringdata_CLASSTWellItemENDCLASS_t", "struct_q_t___w_a_r_n_i_n_g___d_i_s_a_b_l_e___d_e_p_r_e_c_a_t_e_d_1_1qt__meta__stringdata___c_l_a59512ef335d3966525c9e6d2e46fa2a2.html", "struct_q_t___w_a_r_n_i_n_g___d_i_s_a_b_l_e___d_e_p_r_e_c_a_t_e_d_1_1qt__meta__stringdata___c_l_a59512ef335d3966525c9e6d2e46fa2a2" ],
      [ "qt_meta_stringdata_CLASSUIUtilsENDCLASS_t", "struct_q_t___w_a_r_n_i_n_g___d_i_s_a_b_l_e___d_e_p_r_e_c_a_t_e_d_1_1qt__meta__stringdata___c_l_a6a7356b785ee2a3aa20fc92095d14161.html", "struct_q_t___w_a_r_n_i_n_g___d_i_s_a_b_l_e___d_e_p_r_e_c_a_t_e_d_1_1qt__meta__stringdata___c_l_a6a7356b785ee2a3aa20fc92095d14161" ]
    ] ],
    [ "QXlsx", "namespace_q_xlsx.html", [
      [ "AbstractSheetPrivate", "class_q_xlsx_1_1_abstract_sheet_private.html", "class_q_xlsx_1_1_abstract_sheet_private" ],
      [ "ChartPrivate", "class_q_xlsx_1_1_chart_private.html", "class_q_xlsx_1_1_chart_private" ],
      [ "ChartsheetPrivate", "class_q_xlsx_1_1_chartsheet_private.html", "class_q_xlsx_1_1_chartsheet_private" ],
      [ "ContentTypes", "class_q_xlsx_1_1_content_types.html", "class_q_xlsx_1_1_content_types" ],
      [ "DocPropsApp", "class_q_xlsx_1_1_doc_props_app.html", "class_q_xlsx_1_1_doc_props_app" ],
      [ "DocPropsCore", "class_q_xlsx_1_1_doc_props_core.html", "class_q_xlsx_1_1_doc_props_core" ],
      [ "DocumentPrivate", "class_q_xlsx_1_1_document_private.html", "class_q_xlsx_1_1_document_private" ],
      [ "Drawing", "class_q_xlsx_1_1_drawing.html", "class_q_xlsx_1_1_drawing" ],
      [ "DrawingAbsoluteAnchor", "class_q_xlsx_1_1_drawing_absolute_anchor.html", "class_q_xlsx_1_1_drawing_absolute_anchor" ],
      [ "DrawingAnchor", "class_q_xlsx_1_1_drawing_anchor.html", "class_q_xlsx_1_1_drawing_anchor" ],
      [ "DrawingOneCellAnchor", "class_q_xlsx_1_1_drawing_one_cell_anchor.html", "class_q_xlsx_1_1_drawing_one_cell_anchor" ],
      [ "DrawingTwoCellAnchor", "class_q_xlsx_1_1_drawing_two_cell_anchor.html", "class_q_xlsx_1_1_drawing_two_cell_anchor" ],
      [ "FormatPrivate", "class_q_xlsx_1_1_format_private.html", "class_q_xlsx_1_1_format_private" ],
      [ "MediaFile", "class_q_xlsx_1_1_media_file.html", "class_q_xlsx_1_1_media_file" ],
      [ "NumFormatParser", "class_q_xlsx_1_1_num_format_parser.html", null ],
      [ "Relationships", "class_q_xlsx_1_1_relationships.html", "class_q_xlsx_1_1_relationships" ],
      [ "SharedStrings", "class_q_xlsx_1_1_shared_strings.html", "class_q_xlsx_1_1_shared_strings" ],
      [ "SimpleOOXmlFile", "class_q_xlsx_1_1_simple_o_o_xml_file.html", "class_q_xlsx_1_1_simple_o_o_xml_file" ],
      [ "Styles", "class_q_xlsx_1_1_styles.html", "class_q_xlsx_1_1_styles" ],
      [ "Theme", "class_q_xlsx_1_1_theme.html", "class_q_xlsx_1_1_theme" ],
      [ "WorkbookPrivate", "class_q_xlsx_1_1_workbook_private.html", "class_q_xlsx_1_1_workbook_private" ],
      [ "WorksheetPrivate", "class_q_xlsx_1_1_worksheet_private.html", "class_q_xlsx_1_1_worksheet_private" ],
      [ "XlsxAxis", "class_q_xlsx_1_1_xlsx_axis.html", "class_q_xlsx_1_1_xlsx_axis" ],
      [ "XlsxColor", "class_q_xlsx_1_1_xlsx_color.html", "class_q_xlsx_1_1_xlsx_color" ],
      [ "XlsxColumnInfo", "struct_q_xlsx_1_1_xlsx_column_info.html", "struct_q_xlsx_1_1_xlsx_column_info" ],
      [ "XlsxDefineNameData", "struct_q_xlsx_1_1_xlsx_define_name_data.html", "struct_q_xlsx_1_1_xlsx_define_name_data" ],
      [ "XlsxFormatNumberData", "struct_q_xlsx_1_1_xlsx_format_number_data.html", "struct_q_xlsx_1_1_xlsx_format_number_data" ],
      [ "XlsxHyperlinkData", "struct_q_xlsx_1_1_xlsx_hyperlink_data.html", "struct_q_xlsx_1_1_xlsx_hyperlink_data" ],
      [ "XlsxMarker", "struct_q_xlsx_1_1_xlsx_marker.html", "struct_q_xlsx_1_1_xlsx_marker" ],
      [ "XlsxRelationship", "struct_q_xlsx_1_1_xlsx_relationship.html", "struct_q_xlsx_1_1_xlsx_relationship" ],
      [ "XlsxRowInfo", "struct_q_xlsx_1_1_xlsx_row_info.html", "struct_q_xlsx_1_1_xlsx_row_info" ],
      [ "XlsxSeries", "class_q_xlsx_1_1_xlsx_series.html", "class_q_xlsx_1_1_xlsx_series" ],
      [ "XlsxSharedStringInfo", "class_q_xlsx_1_1_xlsx_shared_string_info.html", "class_q_xlsx_1_1_xlsx_shared_string_info" ],
      [ "XlsxSheetFormatProps", "struct_q_xlsx_1_1_xlsx_sheet_format_props.html", "struct_q_xlsx_1_1_xlsx_sheet_format_props" ],
      [ "ZipReader", "class_q_xlsx_1_1_zip_reader.html", "class_q_xlsx_1_1_zip_reader" ],
      [ "ZipWriter", "class_q_xlsx_1_1_zip_writer.html", "class_q_xlsx_1_1_zip_writer" ]
    ] ],
    [ "Ui", "namespace_ui.html", [
      [ "MainWindow", "class_ui_1_1_main_window.html", null ],
      [ "MWellWidget", "class_ui_1_1_m_well_widget.html", null ],
      [ "MWellWindow", "class_ui_1_1_m_well_window.html", null ],
      [ "sinkDialog", "class_ui_1_1sink_dialog.html", null ]
    ] ],
    [ "AbstractOOXmlFile", "class_abstract_o_o_xml_file.html", "class_abstract_o_o_xml_file" ],
    [ "AbstractOOXmlFilePrivate", "class_abstract_o_o_xml_file_private.html", "class_abstract_o_o_xml_file_private" ],
    [ "AbstractSheet", "class_abstract_sheet.html", "class_abstract_sheet" ],
    [ "Cell", "class_cell.html", "class_cell" ],
    [ "CellFormula", "class_cell_formula.html", "class_cell_formula" ],
    [ "CellFormulaPrivate", "class_cell_formula_private.html", "class_cell_formula_private" ],
    [ "CellPrivate", "class_cell_private.html", "class_cell_private" ],
    [ "CellRange", "class_cell_range.html", "class_cell_range" ],
    [ "CellReference", "class_cell_reference.html", "class_cell_reference" ],
    [ "cement", "structcement.html", "structcement" ],
    [ "Chart", "class_chart.html", "class_chart" ],
    [ "Chartsheet", "class_chartsheet.html", "class_chartsheet" ],
    [ "CompHIPRDelegate", "class_comp_h_i_p_r_delegate.html", "class_comp_h_i_p_r_delegate" ],
    [ "CompVIPRDelegate", "class_comp_v_i_p_r_delegate.html", "class_comp_v_i_p_r_delegate" ],
    [ "ConditionalFormatting", "class_conditional_formatting.html", "class_conditional_formatting" ],
    [ "ConditionalFormattingPrivate", "class_conditional_formatting_private.html", "class_conditional_formatting_private" ],
    [ "DataValidation", "class_data_validation.html", "class_data_validation" ],
    [ "DataValidationPrivate", "class_data_validation_private.html", "class_data_validation_private" ],
    [ "Document", "class_document.html", "class_document" ],
    [ "DoubleValidator", "class_double_validator.html", "class_double_validator" ],
    [ "EditableDelegate", "class_editable_delegate.html", "class_editable_delegate" ],
    [ "fluid", "structfluid.html", "structfluid" ],
    [ "Format", "class_format.html", "class_format" ],
    [ "GeometryDelegate", "class_geometry_delegate.html", "class_geometry_delegate" ],
    [ "GradeDelegate", "class_grade_delegate.html", "class_grade_delegate" ],
    [ "HTCCalATIMult", "class_h_t_c_cal_a_t_i_mult.html", "class_h_t_c_cal_a_t_i_mult" ],
    [ "HTCCalculate", "class_h_t_c_calculate.html", "class_h_t_c_calculate" ],
    [ "IQmlObject", "class_i_qml_object.html", "class_i_qml_object" ],
    [ "IQmlSingleton", "class_i_qml_singleton.html", "class_i_qml_singleton" ],
    [ "MainWindow", "class_main_window.html", "class_main_window" ],
    [ "MDeviationPar", "class_m_deviation_par.html", "class_m_deviation_par" ],
    [ "MFlowline", "class_m_flowline.html", "class_m_flowline" ],
    [ "MFlowlineDialog", "class_m_flowline_dialog.html", "class_m_flowline_dialog" ],
    [ "MFlowlinePar", "class_m_flowline_par.html", "class_m_flowline_par" ],
    [ "MJunction", "class_m_junction.html", "class_m_junction" ],
    [ "MJunctionDialog", "class_m_junction_dialog.html", "class_m_junction_dialog" ],
    [ "MSink", "class_m_sink.html", "class_m_sink" ],
    [ "MSinkDialog", "class_m_sink_dialog.html", "class_m_sink_dialog" ],
    [ "MSource", "class_m_source.html", "class_m_source" ],
    [ "MSourceDialog", "class_m_source_dialog.html", "class_m_source_dialog" ],
    [ "MulItem", "class_mul_item.html", "class_mul_item" ],
    [ "MWell", "class_m_well.html", "class_m_well" ],
    [ "MWellCasing", "class_m_well_casing.html", "class_m_well_casing" ],
    [ "MWellDeviation", "class_m_well_deviation.html", "class_m_well_deviation" ],
    [ "MWellHeat", "class_m_well_heat.html", "class_m_well_heat" ],
    [ "MWellPacker", "class_m_well_packer.html", "class_m_well_packer" ],
    [ "MWellReservoir", "class_m_well_reservoir.html", "class_m_well_reservoir" ],
    [ "MWellTunbing", "class_m_well_tunbing.html", "class_m_well_tunbing" ],
    [ "MWellWidget", "class_m_well_widget.html", "class_m_well_widget" ],
    [ "MWellWindow", "class_m_well_window.html", "class_m_well_window" ],
    [ "ReadOnlyDelegate", "class_read_only_delegate.html", "class_read_only_delegate" ],
    [ "RichString", "class_rich_string.html", "class_rich_string" ],
    [ "RichStringPrivate", "class_rich_string_private.html", "class_rich_string_private" ],
    [ "SingletonMixin", "class_singleton_mixin.html", null ],
    [ "sinkDialog", "classsink_dialog.html", "classsink_dialog" ],
    [ "TArrow", "class_t_arrow.html", "class_t_arrow" ],
    [ "TFlowlineItem", "class_t_flowline_item.html", "class_t_flowline_item" ],
    [ "TGraphicsScene", "class_t_graphics_scene.html", "class_t_graphics_scene" ],
    [ "TGraphicsView", "class_t_graphics_view.html", "class_t_graphics_view" ],
    [ "TMultiflowItem", "class_t_multiflow_item.html", "class_t_multiflow_item" ],
    [ "TSinkItem", "class_t_sink_item.html", "class_t_sink_item" ],
    [ "TSourceItem", "class_t_source_item.html", "class_t_source_item" ],
    [ "TTabWidget", "class_t_tab_widget.html", "class_t_tab_widget" ],
    [ "TTreeWidget", "class_t_tree_widget.html", "class_t_tree_widget" ],
    [ "TWellItem", "class_t_well_item.html", "class_t_well_item" ],
    [ "Ui_MainWindow", "class_ui___main_window.html", "class_ui___main_window" ],
    [ "Ui_MWellWidget", "class_ui___m_well_widget.html", "class_ui___m_well_widget" ],
    [ "Ui_MWellWindow", "class_ui___m_well_window.html", "class_ui___m_well_window" ],
    [ "Ui_sinkDialog", "class_ui__sink_dialog.html", "class_ui__sink_dialog" ],
    [ "UIUtils", "class_u_i_utils.html", "class_u_i_utils" ],
    [ "UMultATIMult", "class_u_mult_a_t_i_mult.html", "class_u_mult_a_t_i_mult" ],
    [ "Workbook", "class_workbook.html", "class_workbook" ],
    [ "Worksheet", "class_worksheet.html", "class_worksheet" ],
    [ "XlsxCfRuleData", "class_xlsx_cf_rule_data.html", "class_xlsx_cf_rule_data" ],
    [ "XlsxCfVoData", "class_xlsx_cf_vo_data.html", "class_xlsx_cf_vo_data" ]
];