#ifndef MULTIFLOWLIBRARY_GLOBAL_H
#define MULTIFLOWLIBRARY_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MULTIFLOWLIBRARY_LIBRARY)
#  define ML_PUBLIC Q_DECL_EXPORT
#else
#  define ML_PUBLIC Q_DECL_IMPORT
#endif

#define ML_PRIVATE

#endif // MULTIFLOWLIBRARY_GLOBAL_H
